sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.14.0

before_install:
  - curl -fsSL get.docker.com -o get-docker.sh
  - sudo sh get-docker.sh
  - docker build -t doublefault .

script:
  - docker run -n doublefault_travisci -e "GOOGLE_OAUTH_KEY=" -e "GOOGLE_OAUTH_SECRET=" -v `pwd`:/doublefault doublefault pytest --cov-report term-missing --cov=web --ds=test_settings tests/

after_success:
  - docker exec doublefault_travisci coveralls