version: '2'

services:
  web:
    build: .
    volumes:
      - .:/doublefault
    ports:
      - "8080:8080"
    depends_on:
      - df-postgres
    links:
      - df-postgres
    network_mode: bridge
    command: sh start.sh

  df-postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: doublefault
      POSTGRES_PASSWORD: doublefault
    network_mode: bridge
    ports:
      - "5432:5432"